/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.dbconnect;
import guiinternal.add;
import guiinternal.soldProduct;
import static java.awt.AWTEventMulticaster.add;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author College-PC
 */
public class printPage extends javax.swing.JFrame {

    /**
     * Creates new form delete
     */
    public printPage() {
        initComponents();
//        displaydata();
        seticon();

    }
    
    public String nnm;
    
    Color bodycolor = new Color(153, 204, 255);
    Color headcolor = new Color(255, 153, 153);
    Color hover = new Color(0, 153, 204);

    public void close() {

        this.dispose();
        main m = new main();
        m.setVisible(true);      
        soldProduct up = new soldProduct();        
        m.despane.add(up).setVisible(true);
        m.name.setText(nnm);
        up.report = nnm;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        printer = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        transid = new javax.swing.JLabel();
        fid = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        u_add = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printer.setBackground(new java.awt.Color(255, 153, 153));
        printer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printerMouseExited(evt);
            }
        });

        text.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Print");

        javax.swing.GroupLayout printerLayout = new javax.swing.GroupLayout(printer);
        printer.setLayout(printerLayout);
        printerLayout.setHorizontalGroup(
            printerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );
        printerLayout.setVerticalGroup(
            printerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printerLayout.createSequentialGroup()
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(printer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 30));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("Add Fish Details");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        cancel.setBackground(new java.awt.Color(255, 153, 153));
        cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cancel");
        cancel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 30));

        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, 30));

        jpanel.setBackground(new java.awt.Color(255, 255, 255));
        jpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fish - Copy.png"))); // NOI18N
        jpanel.add(jLabel2);
        jLabel2.setBounds(470, 10, 48, 50);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Transaction ID :");
        jpanel.add(jLabel3);
        jLabel3.setBounds(10, 70, 130, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Fish Code :");
        jpanel.add(jLabel4);
        jLabel4.setBounds(10, 110, 130, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Fish Name :");
        jpanel.add(jLabel5);
        jLabel5.setBounds(10, 150, 130, 30);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Fish Price :");
        jpanel.add(jLabel7);
        jLabel7.setBounds(10, 190, 130, 30);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Buyer ID :");
        jpanel.add(jLabel8);
        jLabel8.setBounds(10, 230, 130, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Buyer Name :");
        jpanel.add(jLabel9);
        jLabel9.setBounds(10, 270, 130, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Transaction Status :");
        jpanel.add(jLabel10);
        jLabel10.setBounds(10, 350, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/aqua1.png"))); // NOI18N
        jpanel.add(jLabel1);
        jLabel1.setBounds(180, 10, 180, 60);

        date.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(date);
        date.setBounds(440, 70, 90, 30);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Buyer Address:");
        jpanel.add(jLabel15);
        jLabel15.setBounds(10, 310, 140, 30);

        transid.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(transid);
        transid.setBounds(160, 70, 140, 30);

        fid.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(fid);
        fid.setBounds(160, 110, 140, 30);

        fname.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(fname);
        fname.setBounds(160, 150, 140, 30);

        stat.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(stat);
        stat.setBounds(160, 350, 140, 30);

        price.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(price);
        price.setBounds(160, 190, 140, 30);

        user.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(user);
        user.setBounds(160, 230, 140, 30);

        uname.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(uname);
        uname.setBounds(160, 270, 140, 30);

        u_add.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jpanel.add(u_add);
        u_add.setBounds(160, 310, 140, 30);

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Transaction Date :");
        jpanel.add(jLabel23);
        jLabel23.setBounds(300, 70, 140, 30);

        jPanel2.add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 540, 390));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/aqua1.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 472));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printerMouseClicked

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print data");
      job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
               if(pageNum>0){
                   
                   return Printable.NO_SUCH_PAGE;
               }
                Graphics2D g2 = (Graphics2D)pg;
                 g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                jpanel.print(g2);
         
               
                return Printable.PAGE_EXISTS;
            }
        });
      
       boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        JOptionPane.showMessageDialog(null, "Printing Success");
        close();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Printing failed");
}   
        }
        


    
    }//GEN-LAST:event_printerMouseClicked

    private void printerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printerMouseEntered
        printer.setBackground(bodycolor);
    }//GEN-LAST:event_printerMouseEntered

    private void printerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printerMouseExited
        printer.setBackground(headcolor);
    }//GEN-LAST:event_printerMouseExited

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        close();
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(bodycolor);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(headcolor);
    }//GEN-LAST:event_cancelMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
          
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel;
    public javax.swing.JLabel date;
    public javax.swing.JLabel fid;
    public javax.swing.JLabel fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpanel;
    public javax.swing.JLabel price;
    private javax.swing.JPanel printer;
    public javax.swing.JLabel stat;
    private javax.swing.JLabel text;
    public javax.swing.JLabel transid;
    public javax.swing.JLabel u_add;
    public javax.swing.JLabel uname;
    public javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/fish.png")));
        setTitle("Aqua Life");
    }
}
